### 模型 Classifier

In [1]:
# 不属于本作业的代码
import torch
import torch.nn as nn
import torch.nn.functional as F
class Classifier(nn.Module):
    def __init__(self, d_model=80, n_spks=600, dropout=0.1):
        super().__init__()
        self.fc1 = nn.Linear(40, 80)
        
    def forward(self, x):
        print('x', x)
        out = self.fc1(x)
        
        return out

x = torch.randn(1, 2, 40)

module = Classifier()
output_tensor = module(x)
print('output_tensor.shape', output_tensor.shape)

x tensor([[[-1.0901,  1.1819,  0.7886,  1.5535, -1.2427,  1.7660,  0.9284,
          -0.7842,  0.0192, -0.6306, -0.9772,  0.6619,  1.2552,  1.8749,
          -0.3533, -0.7700,  1.4728,  1.4153, -0.8875, -0.8448,  1.2200,
           1.1723,  1.0875, -1.4292, -0.0329,  0.4312, -1.1617,  0.6495,
           0.3001, -0.3996, -0.1957, -0.5547, -1.2100, -0.2962,  0.2951,
           0.1526, -0.9361,  0.4924,  0.0291, -1.5464],
         [ 0.7884, -0.7737, -1.1455,  1.2430, -0.1077,  2.3955, -1.0904,
          -0.5161,  1.4699, -0.7851,  0.5706, -1.1925, -1.9294,  1.0363,
           0.5553, -0.7292, -1.8897, -0.4809, -0.6555, -1.4076, -0.5577,
           0.1653,  0.8924,  0.9308, -0.7766,  0.8844, -1.7648,  0.9387,
          -0.3380,  1.9968,  0.5960, -2.3631, -0.1019,  1.1034,  1.3185,
          -1.0731,  0.8066, -0.9332,  1.2089,  0.3577]]])
output_tensor.shape torch.Size([1, 2, 80])


In [4]:
# 不属于该作业的代码
import torch
import random

# 创建一个形状为(3, 4)的torch.FloatTensor对象，数据类型为float32
x = torch.tensor([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]], dtype=torch.float32)

mel = 555
segment_len = 128
start = random.randint(0, mel - segment_len)

print(len(x))
print(x[1:3])
print(start)

b = torch.rand(3,3)#得到的是floattensor值，
print(b)
b = b.long()#得到的是longtensor值
print(b)

print('torch.FloatTensor([speaker])', torch.FloatTensor([44]))
print('torch.FloatTensor([speaker]).long()', torch.FloatTensor([44]).long())

3
tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
53
tensor([[0.6433, 0.8647, 0.9158],
        [0.8107, 0.0056, 0.4446],
        [0.6455, 0.7661, 0.2941]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.FloatTensor([speaker]) tensor([44.])
torch.FloatTensor([speaker]).long() tensor([44])


### pad_sequence

In [30]:
# 不属于该作业的代码
import torch
from torch.nn.utils.rnn import pad_sequence

# 最后一维必须一致，可以理解为 embedding 层
a = torch.ones(2, 3)
b = torch.ones(1, 3)
c = torch.ones(3, 3)

print('c', c)
print('a.shape', a.shape)
print('b.shape', b.shape)
print('c.shape', c.shape)

print(pad_sequence((a, b, c), batch_first=False, padding_value=20).size()) # 如果是()，就是一个元组，里面的 a，b，c 都不是 list
print(pad_sequence([a, b, c], batch_first=False, padding_value=20).size())

# batch_first=True 表示将批次维度放在序列的第一维，便于后续处理。
print(pad_sequence([a, b, c], batch_first=True, padding_value=5))

c tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
a.shape torch.Size([2, 3])
b.shape torch.Size([1, 3])
c.shape torch.Size([3, 3])
torch.Size([3, 3, 3])
torch.Size([3, 3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [5., 5., 5.]],

        [[1., 1., 1.],
         [5., 5., 5.],
         [5., 5., 5.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [20]:
e = torch.tensor([1, 2, 3])
f = torch.tensor([4, 5])

print('e.shape', e.shape)
print('f.shape', f.shape)
print(pad_sequence([e, f], batch_first=True, padding_value=20))

e.shape torch.Size([3])
f.shape torch.Size([2])
tensor([[ 1,  2,  3],
        [ 4,  5, 20]])


使用 pad_sequence: https://blog.csdn.net/Zhao_knight/article/details/120913610

<font color=red> 如果出现报错，是由于 矩阵是由数字组成的矩阵，也就是基本单元都是数字，但是，再高一层次(既是+2 也是-2 个维度)的数据类型是list，而不是数组。</font>

解决：使用 torch.tensor() 对第二层的数据类型做一个类型转换，不适用list

In [26]:
import numpy as np
from torch.nn.utils.rnn import pad_sequence
input_x =[[1,2,3],[4,5,6,7,8],[8,9]]
norm_data_pad = pad_sequence([torch.from_numpy(np.array(x)) for x in input_x], batch_first=True).float()
print(norm_data_pad)

input_x = [torch.tensor([1,2,3]),torch.tensor([4,5,6,7,8]),torch.tensor([8,9])]
norm_data_pad = pad_sequence(input_x, batch_first=True).float()
print(norm_data_pad)

tensor([[1., 2., 3., 0., 0.],
        [4., 5., 6., 7., 8.],
        [8., 9., 0., 0., 0.]])
tensor([[1., 2., 3., 0., 0.],
        [4., 5., 6., 7., 8.],
        [8., 9., 0., 0., 0.]])


### collate_fn

pytorch中collate_fn函数的使用&如何向collate_fn函数传参: https://blog.csdn.net/dong_liuqi/article/details/114521240

### argparse 库

Python：argparse 库高级用法举例和应用详解：https://evzs.com/2024/07/25/Python%EF%BC%9Aargparse%E5%BA%93%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95%E4%B8%BE%E4%BE%8B%E5%92%8C%E5%BA%94%E7%94%A8%E8%AF%A6%E8%A7%A3.html

argparse --- 用于命令行选项、参数和子命令的解析器：https://docs.python.org/zh-cn/3.12/library/argparse.html


In [6]:
# 不属于该作业的代码
import argparse  # 导入argparse库

def main():
    parser = argparse.ArgumentParser(description='示例 1: 基本用法')  # 创建ArgumentParser对象并添加描述
    # 前面没有'-'，属于位置参数。
    # 前面有'-'，属于可选参数。
    parser.add_argument('--name', help='你的名字')  # 添加一个名为name的可选参数

    # 调用parser.parse_args()会读取系统参数：sys.argv[]，命令行调用时是正确参数，而在jupyter notebook中调用时，sys.argv的值为ipykrnel_launcher.py：因此会报错
    # args = parser.parse_args()  # 解析命令行参数

    args = parser.parse_known_args()[0] # 解析命令行参数
    if args.name:  # 如果name参数存在，打印欢迎消息
        print(f"你好, {args.name}!")
    else:  # 如果name参数不存在，提示参数缺失
        print("你没有提供名字.")

if __name__ == "__main__":
    main()

# 运行上面的脚本: python script.py --name Alice

你没有提供名字.


### index_select

In [7]:
# 不属于该作业的代码
# index_select 函数
t = torch.arange(24).reshape(2, 3, 4) # 初始化一个tensor，从0到23，形状为（2,3,4）
print("t--->", t)
 
index = torch.tensor([1, 2]) # 要选取数据的位置
print("index--->", index)

# .reshape(2, 3, 4) 可以看出 2 是第1维，3 是第2维，4是第3维
data1 = t.index_select(1, index) # 第一个参数:从第2维挑选， 第二个参数:从该维中挑选的位置
print("data1--->", data1)
 
data2 = t.index_select(2, index) # 第一个参数:从第3维挑选， 第二个参数:从该维中挑选的位置
print("data2--->", data2)

t---> tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
index---> tensor([1, 2])
data1---> tensor([[[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])
data2---> tensor([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],

        [[13, 14],
         [17, 18],
         [21, 22]]])


In [8]:
# 不属于该作业的代码
# transformer
import torch
# 初始化词嵌入矩阵
vocabulary_size = 5
embedding_dim = 3
embedding_matrix = torch.nn.Parameter(torch.randn(vocabulary_size, embedding_dim))
# 输入索引值
input_indices = torch.LongTensor([[0, 1, 2], [2, 3, 4]])
# 根据输入索引值查找词嵌入向量
# index_select：https://blog.csdn.net/kdongyi/article/details/103099589
# 第一个参数：dim：表示从第几维挑选数据，类型为int值；第二个参数：index：表示从第一个参数维度中的哪个位置挑选数据
embedded_vectors = torch.index_select(embedding_matrix, dim=0, index=input_indices.flatten())
# 将词嵌入向量按照输入索引顺序进行拼接
# .view 相当于 numpy中resize（）的功能，但是用法可能不太一样。
embedded_vectors = embedded_vectors.view(input_indices.size(0), input_indices.size(1), embedding_dim) # size 为 2, 3, 3

print("input_indices.flatten():\n", input_indices.flatten())
print('')

print("Embedding Matrix:\n", embedding_matrix)
print('')

print("Input Indices:\n", input_indices)
print('')

print("input_indices.size:\n", input_indices.size())
print('')

print("input_indices.size(0):\n", input_indices.size(0))
print('')

print("Embedded Vectors:\n", embedded_vectors)

input_indices.flatten():
 tensor([0, 1, 2, 2, 3, 4])

Embedding Matrix:
 Parameter containing:
tensor([[ 0.2906, -0.2304, -0.2201],
        [ 2.3460,  1.2444,  2.0486],
        [ 0.8249, -2.1700,  0.5731],
        [-0.4615,  0.4468, -0.6046],
        [ 1.4969,  0.2865, -0.7065]], requires_grad=True)

Input Indices:
 tensor([[0, 1, 2],
        [2, 3, 4]])

input_indices.size:
 torch.Size([2, 3])

input_indices.size(0):
 2

Embedded Vectors:
 tensor([[[ 0.2906, -0.2304, -0.2201],
         [ 2.3460,  1.2444,  2.0486],
         [ 0.8249, -2.1700,  0.5731]],

        [[ 0.8249, -2.1700,  0.5731],
         [-0.4615,  0.4468, -0.6046],
         [ 1.4969,  0.2865, -0.7065]]], grad_fn=<ViewBackward0>)
